# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agenda_pb2 as agenda__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddContato = channel.unary_unary(
        '/helloworld.Greeter/AddContato',
        request_serializer=agenda__pb2.Contato.SerializeToString,
        response_deserializer=agenda__pb2.Reply.FromString,
        )
    self.ListarContatos = channel.unary_unary(
        '/helloworld.Greeter/ListarContatos',
        request_serializer=agenda__pb2.Request.SerializeToString,
        response_deserializer=agenda__pb2.Lista.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarContatos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddContato': grpc.unary_unary_rpc_method_handler(
          servicer.AddContato,
          request_deserializer=agenda__pb2.Contato.FromString,
          response_serializer=agenda__pb2.Reply.SerializeToString,
      ),
      'ListarContatos': grpc.unary_unary_rpc_method_handler(
          servicer.ListarContatos,
          request_deserializer=agenda__pb2.Request.FromString,
          response_serializer=agenda__pb2.Lista.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
