# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agenda.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agenda.proto',
  package='helloworld',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x61genda.proto\x12\nhelloworld\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x02(\t\"8\n\x07\x43ontato\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x10\n\x08telefone\x18\x02 \x02(\t\x12\r\n\x05idade\x18\x03 \x02(\x05\"+\n\x05Lista\x12\"\n\x05lista\x18\x01 \x03(\x0b\x32\x13.helloworld.Contato2}\n\x07Greeter\x12\x36\n\nAddContato\x12\x13.helloworld.Contato\x1a\x11.helloworld.Reply\"\x00\x12:\n\x0eListarContatos\x12\x13.helloworld.Request\x1a\x11.helloworld.Lista\"\x00')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='helloworld.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='helloworld.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=77,
)


_CONTATO = _descriptor.Descriptor(
  name='Contato',
  full_name='helloworld.Contato',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='helloworld.Contato.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telefone', full_name='helloworld.Contato.telefone', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idade', full_name='helloworld.Contato.idade', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=135,
)


_LISTA = _descriptor.Descriptor(
  name='Lista',
  full_name='helloworld.Lista',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lista', full_name='helloworld.Lista.lista', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=180,
)

_LISTA.fields_by_name['lista'].message_type = _CONTATO
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Contato'] = _CONTATO
DESCRIPTOR.message_types_by_name['Lista'] = _LISTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Reply)
  })
_sym_db.RegisterMessage(Reply)

Contato = _reflection.GeneratedProtocolMessageType('Contato', (_message.Message,), {
  'DESCRIPTOR' : _CONTATO,
  '__module__' : 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Contato)
  })
_sym_db.RegisterMessage(Contato)

Lista = _reflection.GeneratedProtocolMessageType('Lista', (_message.Message,), {
  'DESCRIPTOR' : _LISTA,
  '__module__' : 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Lista)
  })
_sym_db.RegisterMessage(Lista)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=182,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddContato',
    full_name='helloworld.Greeter.AddContato',
    index=0,
    containing_service=None,
    input_type=_CONTATO,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListarContatos',
    full_name='helloworld.Greeter.ListarContatos',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_LISTA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
